apiVersion: v1
kind: Service
metadata:
  name: {{ include "todofrontend.fullname" . }}
  labels:
    app: todo-app-vodafone
    {{- include "todofrontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "todofrontend.selectorLabels" . | nindent 4 }}
